apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-indexer-gateway"
  labels:
    subsquid.io/component: indexer-gateway
    subsquid.io/release: "{{ .Release.Name }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-indexer-gateway"
                port:
                  number: 4010
